esphome:
  name: garage_door_relay
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "REDACTED"
  password: "REDACTED"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Relay"
    password: "REDACTED"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Web server.
web_server:
  port: 80

binary_sensor:
- platform: gpio
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: False
  name: "Sensor puerta garaje"
  id: sensor_garaje
#  internal: true
  device_class: garage_door
  filters:
#    - delayed_on: 30ms
#    - delayed_off: 1s
    - delayed_on_off: 1s

switch:
- platform: gpio
  id: rele_garaje
#  internal: true
  pin:
    number: GPIO21
    inverted: False
  restore_mode: ALWAYS_OFF
  
## inicio parte   
- platform: template
  name: "Apertura Garaje"
  icon: "mdi:garage"
  turn_on_action:
  - switch.turn_on: rele_garaje
  - delay: 0.2s
  - switch.turn_off: rele_garaje

- platform: restart
  name: 'ESPHome Garage Door REBOOT'
## fin parte   

cover:
  - platform: template
    name: Puerta Garaje
    device_class: garage
    lambda: !lambda |-
      if (id(sensor_garaje).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: rele_garaje
      - delay: 0.2s
      - switch.turn_off: rele_garaje
    close_action:
      - switch.turn_on: rele_garaje
      - delay: 0.2s
      - switch.turn_off: rele_garaje
    stop_action:
      - switch.turn_on: rele_garaje
      - delay: 0.2s
      - switch.turn_off: rele_garaje
      
 
